#!/bin/bash

# Parse firewall
# instead having a firewall rules file with hundreds of ips to load , this util checks on firewall rules for the number
# of identical ips from same subnet , and in case it finds more that a specific amount then will ban the 255 ips from that subnet
# with 0/24 on firewall and will delete those unique ips from that subnet on the firewall rules file

# example : on running this script if it finds these ips banned : 185.234.5.34,185.234.5.100,185.234.5.145,185.234.5.3,185.234.5.20
# it will delete the lines from firewall where those ips are and will place a drop rule for the whole subnet , like : 185.234.5.0/24
# This way every ip from 185.234.5.0 - 185.234.5.255  will be banned automatically

# the number of matched ips to ban can be configured here in (mtch) variable witch is set for 5

# your firewall rules file location must be set on this script
# IT REQUIRES IPTABLES INSTALLED
# Script build by peterpt
# https://github.com/peterpt/server-admin-tools

tmpfile="/tmp/ips.tmp"
rmip="/tmp/rmvips.tmp"
firewall="your firewall rules location" # <- configure here your firewall rules file location
firewallbk="/etc/firewall.rules.bk"
deltemp () {
rm -rf "$tmpfile" > /dev/null 2>&1
rm -rf "$rmip" > /dev/null 2>&1
mtch="5" # Number of identical ips on same subnet to match 

}
deltemp
echo "Checking Ip ranges in firewall"
chkrg=$(cat "$firewall" | grep -w "INPUT" | grep -w "DROP" | grep "\-s" | awk '{print$4}' | sort | cut -d"." -f1-3)
cat "$firewall" | grep -w "INPUT" | grep -w "DROP" | grep "\-s" | awk '{print$4}' | sort | cut -d"." -f1-3 | uniq > "$tmpfile"
cntips=$(wc -l "$tmpfile" | awk '{print$1}')
if [[ "$cntips" -ge "1" ]]
then
for i in $(seq "$cntips")
do
rdip=$(sed -n ${i}p "$tmpfile")
nmbip=$(echo "$chkrg" | grep -c "$rdip" | awk '{print$1}') 
if [[ "$nmbip" -ge "$mtch" ]]
then
if [[ ! -f "$rmip" ]]
then
echo "$rdip   $nmbip" > "$rmip"
else
echo "$rdip   $nmbip" >> "$rmip"
fi
fi
done
fi
if [[ ! -f "$rmip" ]]
then
echo "Nothing to be done for now"
deltemp
exit 0
fi
cntrmv=$(wc -l "$rmip" | awk '{print$1}')
echo "Ips sequence to be removed from firewall and replaced by subnet /24"
echo ""
for ir in $(seq "$cntrmv")
do
rdip=$(sed -n ${ir}p "$rmip" | awk '{print$1}')
rdcnt=$(sed -n ${ir}p "$rmip" | awk '{print$2}')
echo "IP range : $rdip  | Single ips in that range : $rdcnt"
done
echo ""
chkban=$(grep -w "\#BANNED" "$firewall")
if [[ -z "$chkban" ]]
then
echo "Tag BANNED was not found in your firewall file"
echo "That tag guides this util to place new subnets after it."
deltemp
exit 0
fi
echo -n "Do You want to continue ? (Y/N) : "
read -r opt
case "$opt" in
Y|YES|yes|Yes|y)
cp "$firewall" "$firewallbk"
for cg in $(seq "$cntrmv")
do
rdip=$(sed -n ${cg}p "$rmip" | awk '{print$1}')
sed -i "/$rdip/d" "$firewall"
sed -i "/#BANNED/a -A INPUT -s $rdip.0/24 -j DROP" "$firewall"
done
iptables-restore "$firewall"
echo "Done"
deltemp
exit 0
;;
N|n|NO|No|no)
deltemp
exit 0
;;
*)
deltemp
exit 0
;;
esac
deltemp
echo "Done"
exit 0





