#!/bin/bash

# Unbanip from fail2ban jails , it will check your current ssh ip and it will clean that ip
# from any jail , or will prompt you an option to insert an ip to clean
# http://github.com/peterpt/serveradmintools

# function to recheck if ip was cleared from jail (both your/other ip)
function checkunban () {
chkjl=$(fail2ban-client status "$rdjl" | grep "$yourip")	
if [[ -z "$chkjl" ]]
then
echo "$yourip was found in : $rdjl and was cleaned"
else
echo "Unable to clean $yourip from $rdjl"
fi	
}	

# function to clean a different ip inserted by user on prompt
function unbanother () {
echo ""
echo -n "Ip to unban : "
read -r yourip	
ip_pattern='^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)$'

	if [[ ! $yourip =~ $ip_pattern ]]
	then
		echo "Invalid IP [$ip]"
		unbanother
	fi

	for i in {1..4}
	do
		if [[ ${BASH_REMATCH[$i]} -gt 255 ]]
		then
			echo "Invalid octet [${BASH_REMATCH[$i]}] in [$ip]"
			unbanother
		fi
	done

	if [[ ${BASH_REMATCH[1]} -eq 0 ]]
	then
		echo "Zero not permitted for first octet in [$ip]"
		unbanother
	fi
	
# Verify how many jails exist and start cleaning the ip inserted manually	
echo "Checking Jails ..."
jailc=$(fail2ban-client status | grep "Jail list" | sed -E 's/^[^:]+:[ \t]+//' | sed 's/,//g' | tr " " "\n" | wc -l)
jailn=$(fail2ban-client status | grep "Jail list" | sed -E 's/^[^:]+:[ \t]+//' | sed 's/,//g' | tr " " "\n")
for i in $(seq $jailc)
do
rdjl=$(echo "$jailn" | sed -n ${i}p)
chkjl=$(fail2ban-client status "$rdjl" | grep "$yourip")
if [[ ! -z "$chkjl" ]]
then
fail2ban-client set "$rdjl" unbanip "$yourip" >/dev/null 2>&1
checkunban
else
echo "$yourip not found in $rdjl"
fi
done		
}


# grabs your ip in case you are connected over ssh and cleans it from jails 
function unbanyou () {
echo -n "-Grabbing your ip ..."
yourip=$(netstat -anp | grep "sshd" | grep "ESTABLISHED" | awk '{print$5}' | sed 's/:/ /' | awk '{print$1}')
if [[ -z "$yourip" ]]
then
echo "Error"
echo "Unable to get your ip from ssh connection"
exit 0
else
echo "Done"
echo "Your ip is : $yourip"
fi
echo "Checking Jails ..."
jailc=$(fail2ban-client status | grep "Jail list" | sed -E 's/^[^:]+:[ \t]+//' | sed 's/,//g' | tr " " "\n" | wc -l)
jailn=$(fail2ban-client status | grep "Jail list" | sed -E 's/^[^:]+:[ \t]+//' | sed 's/,//g' | tr " " "\n")
for i in $(seq $jailc)
do
rdjl=$(echo "$jailn" | sed -n ${i}p)
chkjl=$(fail2ban-client status "$rdjl" | grep "$yourip")
if [[ ! -z "$chkjl" ]]
then
fail2ban-client set "$rdjl" unbanip "$yourip" >/dev/null 2>&1
checkunban
else
echo "$yourip not found in $rdjl"
fi
done
}
clear
echo "-----------Unban IP-----------"
echo "------------------------------"
echo ""
echo "Do You want to search and unban your ip or any other  ?"
echo ""
echo "1 - Your IP (You must be connected using ssh)"
echo "2 - Other ip"
echo "3 - Exit"
echo ""
echo -n "Choose :"
read -r opt
if [[ "$opt" == "1" ]]
then
unbanyou
elif [[ "$opt" == "2" ]]
then
unbanother
elif [[ "$opt" == "3" ]]
then
exit 0
else
exit 0
fi

